services:
  matdev.api:
    image: ${DOCKER_REGISTRY-}matdevapi
    container_name: matdev.api
    build:
      context: .
      dockerfile: matdev.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Database=Host=matdev.database;Port=5432;Database=matdev;Username=postgres;Password=postgres
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - matdev.database
  matdev.database:
    image: postgres:18.3
    container_name: matdev.database
    environment:
      - POSTGRES_DB=matdev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - database_pgdata:/var/lib/postgresql
    ports:
      - "5432:5432"
volumes:
  database_pgdata: { }
  
