// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using matdev.Infrastructure.Data;

#nullable disable

namespace matdev.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260529114028_AddProjectRisks")]
    partial class AddProjectRisks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("matdev.Domain.Entities.BudgetEntities.BudgetCategory", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryID"));

                    b.Property<decimal>("DefaultAlertThreshold")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("CategoryID");

                    b.ToTable("BudgetCategories");
                });

            modelBuilder.Entity("matdev.Domain.Entities.BudgetEntities.BudgetExpenditure", b =>
                {
                    b.Property<int>("ExpenditureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ExpenditureID"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("BudgetCategoryID")
                        .HasColumnType("integer");

                    b.Property<int>("BudgetPlanID")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ExpenditureID");

                    b.HasIndex("BudgetCategoryID");

                    b.HasIndex("BudgetPlanID");

                    b.ToTable("BudgetExpenditures");
                });

            modelBuilder.Entity("matdev.Domain.Entities.BudgetEntities.BudgetPlan", b =>
                {
                    b.Property<int>("PlanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlanID"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ProjectID")
                        .HasColumnType("integer");

                    b.HasKey("PlanID");

                    b.HasIndex("ProjectID");

                    b.ToTable("BudgetPlans");
                });

            modelBuilder.Entity("matdev.Domain.Entities.LabEntities.LabOrder", b =>
                {
                    b.Property<int>("LabOrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LabOrderID"));

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("PlannedCompletionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SampleID")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("StatusID")
                        .HasColumnType("integer");

                    b.HasKey("LabOrderID");

                    b.HasIndex("StatusID");

                    b.ToTable("LabOrders");
                });

            modelBuilder.Entity("matdev.Domain.Entities.LabEntities.LabOrderAssignment", b =>
                {
                    b.Property<int>("LabOrderAssignmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LabOrderAssignmentID"));

                    b.Property<int>("LabOrderID")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectID")
                        .HasColumnType("integer");

                    b.HasKey("LabOrderAssignmentID");

                    b.HasIndex("LabOrderID");

                    b.HasIndex("ProjectID");

                    b.ToTable("LabOrderAssignments");
                });

            modelBuilder.Entity("matdev.Domain.Entities.LabEntities.LabOrderStatus", b =>
                {
                    b.Property<int>("LabOrderStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LabOrderStatusID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("LabOrderStatusID");

                    b.ToTable("LabOrderStatuses");
                });

            modelBuilder.Entity("matdev.Domain.Entities.LookupEntities.IssueType", b =>
                {
                    b.Property<int>("IssueTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IssueTypeID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("IssueTypeID");

                    b.ToTable("IssueTypes");
                });

            modelBuilder.Entity("matdev.Domain.Entities.LookupEntities.Priority", b =>
                {
                    b.Property<int>("PriorityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PriorityID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("PriorityID");

                    b.ToTable("Priorities");
                });

            modelBuilder.Entity("matdev.Domain.Entities.LookupEntities.Status", b =>
                {
                    b.Property<int>("StatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StatusID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("StatusID");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("matdev.Domain.Entities.LookupEntities.Topic", b =>
                {
                    b.Property<int>("TopicID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TopicID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("TopicID");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("matdev.Domain.Entities.LookupEntities.Workpackage", b =>
                {
                    b.Property<int>("WorkpackageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WorkpackageID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("WorkpackageID");

                    b.ToTable("Workpackages");
                });

            modelBuilder.Entity("matdev.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description 1",
                            Name = "Test Product 1",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description 2",
                            Name = "Test Product 2",
                            Price = 29.99m
                        });
                });

            modelBuilder.Entity("matdev.Domain.Entities.Project", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProjectID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByID")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<int?>("IssueTypeID")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("PriorityID")
                        .HasColumnType("integer");

                    b.Property<int?>("ProjectStatusID")
                        .HasColumnType("integer");

                    b.Property<int?>("ResponsibleID")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<int?>("SupportID")
                        .HasColumnType("integer");

                    b.Property<int?>("TopicID")
                        .HasColumnType("integer");

                    b.Property<int?>("WorkpackageID")
                        .HasColumnType("integer");

                    b.HasKey("ProjectID");

                    b.HasIndex("CreatedByID");

                    b.HasIndex("IssueTypeID");

                    b.HasIndex("PriorityID");

                    b.HasIndex("ProjectStatusID");

                    b.HasIndex("ResponsibleID");

                    b.HasIndex("SupportID");

                    b.HasIndex("TopicID");

                    b.HasIndex("WorkpackageID");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("matdev.Domain.Entities.ProjectAssignment", b =>
                {
                    b.Property<int>("ProjectAssignmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProjectAssignmentID"));

                    b.Property<bool>("IsResponsible")
                        .HasColumnType("boolean");

                    b.Property<int>("ProjectID")
                        .HasColumnType("integer");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("ProjectAssignmentID");

                    b.HasIndex("UserID");

                    b.HasIndex("ProjectID", "UserID")
                        .IsUnique();

                    b.ToTable("ProjectAssignments");
                });

            modelBuilder.Entity("matdev.Domain.Entities.ProjectRisk", b =>
                {
                    b.Property<int>("RiskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RiskID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<int>("ProjectID")
                        .HasColumnType("integer");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("RiskID");

                    b.HasIndex("ProjectID");

                    b.ToTable("ProjectRisks");
                });

            modelBuilder.Entity("matdev.Domain.Entities.TaskEntities.TaskAssignment", b =>
                {
                    b.Property<int>("TaskAssignmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TaskAssignmentID"));

                    b.Property<int>("TaskID")
                        .HasColumnType("integer");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("TaskAssignmentID");

                    b.HasIndex("TaskID");

                    b.HasIndex("UserID");

                    b.ToTable("TaskAssignments");
                });

            modelBuilder.Entity("matdev.Domain.Entities.TaskEntities.TaskCategory", b =>
                {
                    b.Property<int>("TaskCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TaskCategoryID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("TaskCategoryID");

                    b.ToTable("TaskCategories");
                });

            modelBuilder.Entity("matdev.Domain.Entities.TaskEntities.TaskDependency", b =>
                {
                    b.Property<int>("TaskDependencyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TaskDependencyID"));

                    b.Property<int>("DependencyType")
                        .HasColumnType("integer");

                    b.Property<int>("LagTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("PredecessorID")
                        .HasColumnType("integer");

                    b.Property<int>("SuccessorID")
                        .HasColumnType("integer");

                    b.HasKey("TaskDependencyID");

                    b.HasIndex("PredecessorID");

                    b.HasIndex("SuccessorID");

                    b.ToTable("TaskDependencies");
                });

            modelBuilder.Entity("matdev.Domain.Entities.TaskEntities._Task", b =>
                {
                    b.Property<int>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TaskID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsMilestone")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("ParentID")
                        .HasColumnType("integer");

                    b.Property<int?>("PriorityID")
                        .HasColumnType("integer");

                    b.Property<decimal>("Progress")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("ProjectID")
                        .HasColumnType("integer");

                    b.Property<int?>("RequesterID")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("StatusID")
                        .HasColumnType("integer");

                    b.Property<int?>("TaskCategoryID")
                        .HasColumnType("integer");

                    b.HasKey("TaskID");

                    b.HasIndex("ParentID");

                    b.HasIndex("PriorityID");

                    b.HasIndex("ProjectID");

                    b.HasIndex("RequesterID");

                    b.HasIndex("StatusID");

                    b.HasIndex("TaskCategoryID");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("matdev.Domain.Entities.TimeEntry", b =>
                {
                    b.Property<int>("TimeEntryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TimeEntryID"));

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("Hours")
                        .HasColumnType("real");

                    b.Property<int>("TaskID")
                        .HasColumnType("integer");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("TimeEntryID");

                    b.HasIndex("TaskID");

                    b.HasIndex("UserID");

                    b.ToTable("TimeEntries");
                });

            modelBuilder.Entity("matdev.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("matdev.Domain.Entities.BudgetEntities.BudgetExpenditure", b =>
                {
                    b.HasOne("matdev.Domain.Entities.BudgetEntities.BudgetCategory", "BudgetCategory")
                        .WithMany("Expenditures")
                        .HasForeignKey("BudgetCategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("matdev.Domain.Entities.BudgetEntities.BudgetPlan", "BudgetPlan")
                        .WithMany("Expenditures")
                        .HasForeignKey("BudgetPlanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BudgetCategory");

                    b.Navigation("BudgetPlan");
                });

            modelBuilder.Entity("matdev.Domain.Entities.BudgetEntities.BudgetPlan", b =>
                {
                    b.HasOne("matdev.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("matdev.Domain.Entities.LabEntities.LabOrder", b =>
                {
                    b.HasOne("matdev.Domain.Entities.LabEntities.LabOrderStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Status");
                });

            modelBuilder.Entity("matdev.Domain.Entities.LabEntities.LabOrderAssignment", b =>
                {
                    b.HasOne("matdev.Domain.Entities.LabEntities.LabOrder", "LabOrder")
                        .WithMany()
                        .HasForeignKey("LabOrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("matdev.Domain.Entities.Project", "Project")
                        .WithMany("LabOrderAssigments")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LabOrder");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("matdev.Domain.Entities.Project", b =>
                {
                    b.HasOne("matdev.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("matdev.Domain.Entities.LookupEntities.IssueType", "IssueType")
                        .WithMany()
                        .HasForeignKey("IssueTypeID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("matdev.Domain.Entities.LookupEntities.Priority", "Priority")
                        .WithMany()
                        .HasForeignKey("PriorityID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("matdev.Domain.Entities.LookupEntities.Status", "ProjectStatus")
                        .WithMany()
                        .HasForeignKey("ProjectStatusID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("matdev.Domain.Entities.User", "Responsible")
                        .WithMany()
                        .HasForeignKey("ResponsibleID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("matdev.Domain.Entities.User", "Support")
                        .WithMany()
                        .HasForeignKey("SupportID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("matdev.Domain.Entities.LookupEntities.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("matdev.Domain.Entities.LookupEntities.Workpackage", "Workpackage")
                        .WithMany()
                        .HasForeignKey("WorkpackageID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");

                    b.Navigation("IssueType");

                    b.Navigation("Priority");

                    b.Navigation("ProjectStatus");

                    b.Navigation("Responsible");

                    b.Navigation("Support");

                    b.Navigation("Topic");

                    b.Navigation("Workpackage");
                });

            modelBuilder.Entity("matdev.Domain.Entities.ProjectAssignment", b =>
                {
                    b.HasOne("matdev.Domain.Entities.Project", "Project")
                        .WithMany("ProjectAssignments")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("matdev.Domain.Entities.User", "User")
                        .WithMany("ProjectAssignments")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("matdev.Domain.Entities.ProjectRisk", b =>
                {
                    b.HasOne("matdev.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("matdev.Domain.Entities.TaskEntities.TaskAssignment", b =>
                {
                    b.HasOne("matdev.Domain.Entities.TaskEntities._Task", "Task")
                        .WithMany("Assigments")
                        .HasForeignKey("TaskID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("matdev.Domain.Entities.User", "User")
                        .WithMany("TaskAssigments")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("matdev.Domain.Entities.TaskEntities.TaskDependency", b =>
                {
                    b.HasOne("matdev.Domain.Entities.TaskEntities._Task", "Predecessor")
                        .WithMany()
                        .HasForeignKey("PredecessorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("matdev.Domain.Entities.TaskEntities._Task", "Successor")
                        .WithMany()
                        .HasForeignKey("SuccessorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Predecessor");

                    b.Navigation("Successor");
                });

            modelBuilder.Entity("matdev.Domain.Entities.TaskEntities._Task", b =>
                {
                    b.HasOne("matdev.Domain.Entities.TaskEntities._Task", "ParentTask")
                        .WithMany("Subtasks")
                        .HasForeignKey("ParentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("matdev.Domain.Entities.LookupEntities.Priority", "Priority")
                        .WithMany()
                        .HasForeignKey("PriorityID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("matdev.Domain.Entities.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("matdev.Domain.Entities.User", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("matdev.Domain.Entities.LookupEntities.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("matdev.Domain.Entities.TaskEntities.TaskCategory", "TaskCategory")
                        .WithMany()
                        .HasForeignKey("TaskCategoryID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ParentTask");

                    b.Navigation("Priority");

                    b.Navigation("Project");

                    b.Navigation("Requester");

                    b.Navigation("Status");

                    b.Navigation("TaskCategory");
                });

            modelBuilder.Entity("matdev.Domain.Entities.TimeEntry", b =>
                {
                    b.HasOne("matdev.Domain.Entities.TaskEntities._Task", "Task")
                        .WithMany("TimeEntries")
                        .HasForeignKey("TaskID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("matdev.Domain.Entities.User", "User")
                        .WithMany("TimeEntries")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("matdev.Domain.Entities.BudgetEntities.BudgetCategory", b =>
                {
                    b.Navigation("Expenditures");
                });

            modelBuilder.Entity("matdev.Domain.Entities.BudgetEntities.BudgetPlan", b =>
                {
                    b.Navigation("Expenditures");
                });

            modelBuilder.Entity("matdev.Domain.Entities.Project", b =>
                {
                    b.Navigation("LabOrderAssigments");

                    b.Navigation("ProjectAssignments");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("matdev.Domain.Entities.TaskEntities._Task", b =>
                {
                    b.Navigation("Assigments");

                    b.Navigation("Subtasks");

                    b.Navigation("TimeEntries");
                });

            modelBuilder.Entity("matdev.Domain.Entities.User", b =>
                {
                    b.Navigation("ProjectAssignments");

                    b.Navigation("TaskAssigments");

                    b.Navigation("TimeEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
